import random

from faker import Faker


def generate_post_code() -> str:
    """
    Generate a random 10-digit post code.

    Returns:
        str: A string containing 10 random digits
    """
    return "".join(str(random.randint(0, 9)) for _ in range(10))


def generate_first_name(post_code: str) -> str:
    """
    Generate a first name based on a post code.

    The name is generated by splitting the post code into 5 groups of 2 digits,
    converting each group to a letter using modulo 26 operation.

    Args:
        post_code (str): A 10-digit post code

    Returns:
        str: A generated first name (5 characters)
    """
    groups = [post_code[i:i+2] for i in range(0, 10, 2)]
    name = ""
    for group in groups:
        num = int(group)
        letter = chr((num % 26) + ord('a'))
        name += letter
    return name


def generate_last_name() -> str:
    """
    Generate a random last name.

    Returns:
        str: A random last name
    """
    fake = Faker('en_US')
    last_name = fake.last_name()
    return last_name
